In [24]:
import pandas as pd
import os

path = '/raid/elhamod/Butterflies2/Datasets/LowResolution'
fileName = 'aaw4967_tables_s1_to_s11.xlsx - Table S1.csv'

# get dataframe
fileFullPath = os.path.join(path, fileName)
df = pd.read_csv(fileFullPath) 

#clean up
df = df[2:]
df.columns = df.iloc[0]
df = df[1:]

# make readable
df['FullSubspecies'] = df['Species'] + ' ' + df['Subspecies']
df = df.drop(columns=['Species', 'Subspecies', 'Subspecies number'])
df = df.set_index('FullSubspecies')

# extract matrix of connectivity
df2 = df.astype(int).to_numpy()

# display
df

2                         aglaope amalfreda amandus amaryllis amphitrite  \
FullSubspecies                                                             
melpomene aglaope               0         0       0         0          0   
erato amalfreda                 0         0       0         0          0   
melpomene amandus               0         0       0         0          0   
melpomene amaryllis             0         0       0         0          0   
erato amphitrite                0         0       0         0          0   
melpomene burchelli             0         0       1         0          0   
erato colombina                 0         0       0         0          0   
erato cyrbia                    0         0       0         0          0   
melpomene cythera               0         0       0         0          0   
erato demophoon                 0         0       0         0          0   
erato dignus                    0         0       0         0          0   
melpomene ecuadorensis          0         0       0         0          0   
erato emma                      0         0       0         0          0   
erato erato                     0         0       0         0          0   
erato etylus                    0         0       0         0          0   
erato favorinus                 0         0       0         1          0   
erato favorinusxlativitta       0         0       0         0          0   
melpomene flagrans              0         0       0         0          0   
erato guarica                   0         0       0         0          0   
erato hydara                    0         0       0         0          0   
erato lativitta                 1         0       0         0          0   
erato luscombei                 0         0       0         0          0   
melpomene malleti               0         0       0         0          0   
melpomene melpomene             0         0       0         0          0   
erato microclea                 0         0       0         0          0   
melpomene nanna                 0         0       1         0          0   
erato notabilis                 0         0       0         0          0   
melpomene penelope              0         0       0         0          0   
erato petiverana                0         0       0         0          0   
erato phyllis                   0         0       1         0          0   
melpomene plesseni              0         0       0         0          0   
melpomene rosina                0         0       0         0          0   
melpomene schunkei              0         0       0         0          0   
melpomene thelxiopeia           0         0       0         0          0   
erato venus                     0         0       0         0          0   
erato venustus                  0         0       0         0          0   
melpomene vulcanus              0         0       0         0          0   
melpomene xenoclea              0         0       0         0          0   

2                         burchelli colombina cyrbia cythera demophoon  ...  \
FullSubspecies                                                          ...   
melpomene aglaope                 0         0      0       0         0  ...   
erato amalfreda                   0         0      0       0         0  ...   
melpomene amandus                 1         0      0       0         0  ...   
melpomene amaryllis               0         0      0       0         0  ...   
erato amphitrite                  0         0      0       0         0  ...   
melpomene burchelli               0         0      0       0         0  ...   
erato colombina                   0         0      0       0         0  ...   
erato cyrbia                      0         0      0       1         0  ...   
melpomene cythera                 0         0      1       0         0  ...   
erato demophoon                   0         0      0       0         0  ...   
erato dignu

In [25]:
# display matrix
df2

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [26]:
# get components

from scipy.sparse.csgraph import connected_components
from scipy.sparse import csr_matrix

n_components, labels = connected_components(csgraph=csr_matrix(df2), directed=False, return_labels=True)

In [27]:
labels

array([ 0,  1,  2,  3,  4,  2,  5,  6,  6,  7,  8,  9, 10, 11,  9,  3, 12,
       13, 14, 15,  0, 16, 17, 15, 18,  2, 19, 20,  7,  2, 19,  7, 21, 11,
       22, 20, 22, 18], dtype=int32)

In [28]:
n_components

23

In [30]:
df.index[0]

'melpomene aglaope'

In [31]:
import torch 

tensor = torch.tensor([[3,5,1,2],[3,1,5,3],[7,5,8,3]],dtype=torch.float)
print(tensor)
tensor.apply_(lambda x: (x+0.2))
print(tensor)

tensor([[3., 5., 1., 2.],
        [3., 1., 5., 3.],
        [7., 5., 8., 3.]])
tensor([[3.2000, 5.2000, 1.2000, 2.2000],
        [3.2000, 1.2000, 5.2000, 3.2000],
        [7.2000, 5.2000, 8.2000, 3.2000]])
